<p><?=$this->session->flashdata('flasherror');?></p>
<p><?=$this->session->flashdata('flashconfirm');?>
<?=form_open();?>
<?="Въведете име на нов курс:";?>
<?=form_input('course_name')."<br/>";?>
 <?=form_error('course_name');?>
<?=form_submit('add','Добавете курс');?>
<?=form_submit('cancel','Отказ');?>
<?=form_submit('update','Обнови');?>
<?=form_close();?>
<p><?=anchor('Course','Изход');?></p>
